name: WorldBorder
author: Brettflan
description: Efficient, feature-rich plugin for limiting the size of your worlds.
version: 1.5.2
main: com.wimbli.WorldBorder.WorldBorder
softdepend:
  - Essentials
  - GroupManager
  - Permissions
commands:
  wborder:
    description: Primary command for WorldBorder.
    aliases: [worldborder, wb]
    usage: |
           /<command> - list available commands (show help).
           /<command> set <radius> - set world border, centered on you.
           /<command> [world] set <radius> <x> <z> - set world border.
           /<command> [world] radius <radius> - change world's border radius.
           /<command> [world] clear - remove border for this world.
           /<command> clear all - remove border for all worlds.
           /<command> list - show border information for all worlds.
           /<command> shape <round|square> - set the default border shape.
           /<command> getmsg - display border message.
           /<command> setmsg <text> - set border message.
           /<command> knockback <distance> - how far to move the player back.
           /<command> whoosh <on/off> - turn knockback effect on or off.
           /<command> delay <amount> - time between border checks.
           /<command> wshape [world] <round|square|default> - override shape.
           /<command> [world] fill [freq] [pad] - generate world out to border.
           /<command> [world] trim [freq] [pad] - trim world outside of border.
           /<command> debug <on/off> - turn debug mode on or off.
permissions:
  worldborder.*:
    description: Grants all WorldBorder permissions, except worldborder.ignoreborder
    children:
      worldborder.set: true
      worldborder.radius: true
      worldborder.clear: true
      worldborder.list: true
      worldborder.shape: true
      worldborder.getmsg: true
      worldborder.setmsg: true
      worldborder.reload: true
      worldborder.debug: true
      worldborder.knockback: true
      worldborder.delay: true
      worldborder.wshape: true
      worldborder.fill: true
      worldborder.trim: true
      worldborder.help: true
      worldborder.whoosh: true
  worldborder.set:
    description: Can set borders for any world
    default: op
  worldborder.radius:
    description: Can set the radius of an existing border
    default: op
  worldborder.clear:
    description: Can remove any border
    default: op
  worldborder.list:
    description: Can view a list of all borders
    default: op
  worldborder.shape:
    description: Can set the default shape (round or square) for all borders
    default: op
  worldborder.getmsg:
    description: Can view the border crossing message
    default: op
  worldborder.setmsg:
    description: Can set the border crossing message
    default: op
  worldborder.reload:
    description: Can force the plugin to reload from the config file
    default: op
  worldborder.debug:
    description: Can enable/disable debug output to console
    default: op
  worldborder.knockback:
    description: Can set the knockback distance for border crossings
    default: op
  worldborder.delay:
    description: Can set the frequency at which the plugin checks for border crossings
    default: op
  worldborder.wshape:
    description: Can set an overriding border shape for a single world
    default: op
  worldborder.fill:
    description: Can fill in (generate) any missing map chunks out to the border
    default: op
  worldborder.trim:
    description: Can trim (remove) any excess map chunks outside of the border
    default: op
  worldborder.help:
    description: Can view the command reference help pages
    default: op
  worldborder.whoosh:
    description: Can enable/disable "whoosh" knockback effect
    default: op
  worldborder.ignoreborder:
    description: Can move outside border
    default: op
